# Generated by Django 5.1.5 on 2025-03-28 10:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_active_coupon_activo_and_more'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
