# Generated by Django 5.1.5 on 2025-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_orden_coupon_orden_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='stock_reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('fallida', 'Fallida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
