services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - larev-network

  redis-server:
    image: redis:latest
    container_name: redis-server
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - larev-network
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"  # Interfaz web de RabbitMQ
    networks:
      - larev-network
  celery_worker:
    build: .
    command: sh -c "./wait-for-it.sh rabbitmq:5672 -- celery -A larev worker --loglevel=info"
    volumes:
      - /var/www/larev:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    environment:
      - DEBUG=False
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=172.18.0.4
      - DB_PORT=5432
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - rabbitmq
      - redis-server
    networks:
      - larev-network

volumes:
  postgres_data:
  redis-data:

networks:
  larev-network:
    driver: bridge