# Generated by Django 5.1.4 on 2025-01-04 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de la categoría (se optimizará automáticamente).', null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del producto.')),
                ('imagen1', models.ImageField(blank=True, help_text='Primera imagen del producto (se optimizará automáticamente).', null=True, upload_to='productos/')),
                ('imagen2', models.ImageField(blank=True, help_text='Segunda imagen del producto (opcional).', null=True, upload_to='productos/')),
                ('is_active', models.BooleanField(default=True, help_text='Definir si el producto está activo o no.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto.', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=uuid.uuid4, editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(help_text="Nombre de la variante, e.g., 'Lemon Haze 5g'.", max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de esta variante.', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad en stock.')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en gramos, si aplica (para flores o resina).', max_digits=5, null=True)),
                ('talla', models.CharField(blank=True, help_text='Talla, si aplica (para ropa).', max_length=10, null=True)),
                ('imagen1', models.ImageField(blank=True, help_text='Imagen de la variante (opcional, se usa si no hay imagen del producto).', null=True, upload_to='variantes/')),
                ('imagen2', models.ImageField(blank=True, help_text='Imagen de la variante (opcional, se usa si no hay imagen del producto).', null=True, upload_to='variantes/')),
                ('producto', models.ForeignKey(help_text='Producto principal al que pertenece esta variante.', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
            },
        ),
    ]
