# Generated by Django 5.1.5 on 2025-03-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de la subcategoría (opcional).', null=True, upload_to='subcategorias/')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece la subcategoría.', on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, help_text='Subcategoría a la que pertenece el producto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='tienda.subcategoria'),
        ),
    ]
