# Generated by Django 5.1.4 on 2025-01-23 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en gramos, si aplica (para flores o resina).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
