# Generated by Django 5.1.4 on 2025-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'slug')},
        ),
    ]
