# Generated by Django 5.1.4 on 2025-02-13 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='La Revolución Verde CBD', max_length=255)),
                ('descripcion', models.TextField(default='La Revolución Verde CBD es una destacada tienda especializada en productos derivados del cáñamo.', help_text='Breve descripción de la tienda y sus valores.')),
                ('mision', models.TextField(default='Nuestro compromiso es proporcionar productos que promuevan el bienestar y la salud.', help_text='La misión de la tienda.')),
                ('vision', models.TextField(default='Creemos en los beneficios del CBD y nos esforzamos por educar a nuestra comunidad.', help_text='La visión de la tienda.')),
                ('ubicaciones', models.TextField(default='[{"ciudad": "Donostia-San Sebastián", "direccion": "Calle San Francisco 54"}, {"ciudad": "Vitoria-Gasteiz", "direccion": "Centro Comercial Dendaraba, local 5"}]', help_text="Lista de ubicaciones en formato JSON. Ejemplo: [{'ciudad': 'Donostia', 'direccion': 'Calle San Francisco 54'}]")),
            ],
        ),
        migrations.CreateModel(
            name='EmailMFADevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto_variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productovariante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'producto_variante')},
            },
        ),
    ]
