# Generated by Django 5.1.4 on 2025-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='La Revolución Verde CBD', max_length=255)),
                ('descripcion', models.TextField(default='La Revolución Verde CBD es una destacada tienda especializada en productos derivados del cáñamo.', help_text='Breve descripción de la tienda y sus valores.')),
                ('mision', models.TextField(default='Nuestro compromiso es proporcionar productos que promuevan el bienestar y la salud.', help_text='La misión de la tienda.')),
                ('vision', models.TextField(default='Creemos en los beneficios del CBD y nos esforzamos por educar a nuestra comunidad.', help_text='La visión de la tienda.')),
                ('ubicaciones', models.TextField(default='[{"ciudad": "Donostia-San Sebastián", "direccion": "Calle San Francisco 54"}, {"ciudad": "Vitoria-Gasteiz", "direccion": "Centro Comercial Dendaraba, local 5"}]', help_text="Lista de ubicaciones en formato JSON. Ejemplo: [{'ciudad': 'Donostia', 'direccion': 'Calle San Francisco 54'}]")),
            ],
        ),
    ]
