# Generated by Django 5.1.5 on 2025-03-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_from',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_to',
            new_name='fecha_inicio',
        ),
    ]
