# Generated by Django 5.1.4 on 2025-01-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(default='desconocida', max_length=100),
            preserve_default=False,
        ),
    ]
