# Generated by Django 5.1.4 on 2025-01-26 17:45

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
