# Generated by Django 5.1.5 on 2025-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_direccion_es_direccion_tienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(choices=[('ES', 'España')], default='ES', max_length=2),
        ),
    ]
