# Generated by Django 5.1.4 on 2025-01-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_direccion_provincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='nombre_completo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='direccion',
            name='apellido',
            field=models.CharField(default='doe', max_length=150),
            preserve_default=False,
        ),
    ]
