# Generated by Django 5.1.4 on 2025-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_nombre_completo_direccion_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
