# Generated by Django 5.1.4 on 2025-01-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_direccion_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='email',
            field=models.EmailField(default='a@a.com', max_length=254),
            preserve_default=False,
        ),
    ]
